apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.global.frontend.port.external }}
      protocol: TCP
      targetPort: {{ .Values.global.frontend.port.internal }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: momo-store
