kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  .dockerconfigjson: >-
    {{ .Values.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
