global:
  environment: production
  backend:
    port:
      internal: 8081
      external: 8081
  frontend:
    port:
      internal: 80
      external: 80

ingress:
  className: "nginx"
  host: "mgumerov-momo-store.ru"